### ISSUE TITLE
App launched Successfully but when i clicked on object app crashes and below error emerges 

### ISSUE THREAD

**Issue by harshal00685** [pramod722445/ImagePro2#2]
2022-02-10 15:17:02.387 32619-32619/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2022-02-10 15:17:02.556 32619-32619/opencv.org E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
2022-02-10 15:17:24.077 32619-32619/opencv.org E/AndroidRuntime: FATAL EXCEPTION: main
    Process: opencv.org, PID: 32619
    java.lang.RuntimeException: Unable to start activity ComponentInfo{opencv.org/com.example.skincancerpro.CameraActivity}: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3073)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model
        at org.tensorflow.lite.NativeInterpreterWrapper.createModelWithBuffer(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:277)
        at com.example.skincancerpro.imageClassification.<init>(imageClassification.java:47)
        at com.example.skincancerpro.CameraActivity.onCreate(CameraActivity.java:74)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2941)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3073) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7025) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by 01fe19bcs258** [comment]
did you get any solution for this problem
i am also faceing the same
